#
# CivetWeb server configuration
#
[civetweb-options]

# Reference: https://github.com/civetweb/civetweb/blob/master/docs/api/mg_start.md

listening_ports=8989
request_timeout_ms=10000
enable_auth_domain_check=no
decode_url=no

[civetweb-features]

# Reference: https://github.com/civetweb/civetweb/blob/master/docs/api/mg_init_library.md

files=0
tls=1
cgi=0
ipv6=1
websocket=0
lua=0
ssjs=0
cache=1
stats=0
compression=1
http2=0
domain=0
all=0

#
# Default headers for all responses
#
[response-headers]

#
# Extra HTTP headers for file download.
#
[http-download-headers]
Cache-Control=public, max-age=31536000

[modules]
httpd=udjat-module-civetweb
http=udjat-module-civetweb

[authentication]
engine=github

allow-cache=1

# ---- Github OAuth engine ----
endpoint=https://github.com/login/oauth/authorize?client_id=${client-id}&state=${authentication-state}

# Get token
get-token-url=https://github.com/login/oauth/access_token?client_id=${client-id}&client_secret=${client-secret}&code=${authentication-code}
get-token-method=get
get-token-payload=

# Get user
get-user-account=https://api.github.com/user

# Must match the github's registered callback
redirect-uri=http://127.0.0.1:8989/oauth2/callback

# Github secrets
client-id=YOUR-CLIENT-ID
client-secret=YOUR-CLIENT-SECRET
